export enum MetadataValidationStatus {
  URL_NOT_FOUND = 'URL_NOT_FOUND',
  INVALID_JSONLD = 'INVALID_JSONLD',
  INVALID_HASH = 'INVALID_HASH',
  INCORRECT_FORMAT = 'INCORRECT_FORMAT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BLOCKED_URL = 'BLOCKED_URL',
}