#!/nix/store/vqvj60h076bhqj6977caz0pfxs6543nb-bash-5.2-p15/bin/bash
set -euo pipefail

export CARDANO_NODE_SOCKET_PATH="/node-ipc/node.socket"





if [ ! -z "${RESTORE_SNAPSHOT:-}" ]; then
SNAPSHOT_BASENAME="$(basename "$RESTORE_SNAPSHOT")"
RESTORED_MARKER="$SNAPSHOT_BASENAME.restored"
if [ ! -f "$RESTORED_MARKER" ]; then
  if [[ "$RESTORE_SNAPSHOT" =~ ^https://.* ]]; then
    echo "Downloading snapshot $RESTORE_SNAPSHOT ..."
    /nix/store/6g6s5cqbvk1nw2y2c8lpbn95sk0w24f9-curl-8.2.1-bin/bin/curl -LOC - "$RESTORE_SNAPSHOT"

    /nix/store/6g6s5cqbvk1nw2y2c8lpbn95sk0w24f9-curl-8.2.1-bin/bin/curl -LO "$RESTORE_SNAPSHOT.sha256sum"
    /nix/store/apn3p2b40xvirn7w740wv2gy330ppib5-coreutils-9.3/bin/sha256sum -c "$SNAPSHOT_BASENAME.sha256sum"

    

    SNAPSHOT="$SNAPSHOT_BASENAME"
  else
    SNAPSHOT="$RESTORE_SNAPSHOT"
  fi
  rm -f /var/lib/cexplorer/*.lstate
  /nix/store/1bys3yjgm97yxy91sfy8f5law41fyif9-postgresql-setup.sh --restore-snapshot "$SNAPSHOT" /var/lib/cexplorer
  touch $RESTORED_MARKER
  rm -f $SNAPSHOT{,.sha256sum,.asc}
fi
fi


if [[ -n "${WAIT_FOR_NODE_SYNC:-}" ]]
then
  until [ -S $CARDANO_NODE_SOCKET_PATH ]; do
    echo Waiting for $CARDANO_NODE_SOCKET_PATH
    sleep 10
  done
  # from scripts/postgresql-setup.sh
  export PGHOST=$(cut -d ":" -f 1 "${PGPASSFILE}")
  export PGPORT=$(cut -d ":" -f 2 "${PGPASSFILE}")
  export PGDATABASE=$(cut -d ":" -f 3 "${PGPASSFILE}")
  user=$(cut -d ":" -f 4 "${PGPASSFILE}")
  if [ "$user" != "*" ]; then
    export PGUSER=$user
  fi;
  DB_MAX_BLOCK=$(psql -h $PGHOST $PGDATABASE -U $PGUSER -t -c 'select max (block_no) from block;')
  NODE_CUR_BLOCK=0
  while [ $NODE_CUR_BLOCK -lt $DB_MAX_BLOCK ]; do
    NODE_STATUS="$(cardano-cli query tip --testnet-magic $(jq '.networkMagic' /nix/store/558hxsvn739289w35s5nhy8p89iispb4-shelley-genesis.json) 2>/dev/null || true)"
    NODE_CUR_BLOCK="$(jq -e -r '.block' <<<"$NODE_STATUS" 2>/dev/null || true)"
    echo "Waiting... Sync progress at $NODE_CUR_BLOCK /$DB_MAX_BLOCK"
    sleep 10
  done
fi

mkdir -p log-dir
if [[ "${DISABLE_LEDGER:-N}" == "Y" ]]; then
  LEDGER_OPTS="--disable-ledger"
else
  LEDGER_OPTS="--state-dir /var/lib/cexplorer"
fi

exec /nix/store/hjlmcj93mxvl1wqfsmac1pj9rfk106hw-cardano-db-sync-exe-cardano-db-sync-13.2.0.0/bin/cardano-db-sync \
    --config /configuration/db-sync-config.json \
    --socket-path "$CARDANO_NODE_SOCKET_PATH" \
    --schema-dir /nix/store/4xzm921ryfrvp73j86alrq8rkk14h7s6-schema \
    ${LEDGER_OPTS} \
    ${EXTRA_DB_SYNC_ARGS:-}

