export const IMAGES = {
  appLogo: "/images/SanchoLogo.png",
  appLogoWithoutText: "/images/AppLogoWithoutText.png",
  bgBlue: "/images/BGBlue.png",
  bgOrange: "/images/BGOrange.png",
  errorPageImage: "/images/ErrorPageImage.png",
  heroImage: "/images/HeroImage.png",
  soleVoterImage: "/images/GovActionsSoleVoter.png",
  govActionDefaultImage: "/images/GovActionDefault.png",
  govActionDelegateImage: "/images/GovActionDelegate.png",
  govActionListImage: "/images/GovActionList.png",
  govActionRegisterImage: "/images/GovActionRegister.png",
  successImage: "/images/Success.png",
  warningImage: "/images/Warning.png",
  warningYellowImage: "/images/WarningYellow.png",
};
