export const IMAGES = {
  appLogo: "/images/CardanoLogo.svg",
  appLogoWithoutText: "/images/AppLogoWithoutText.webp",
  bgBlue: "/images/BGBlue.webp",
  bgOrange: "/images/BGOrange.webp",
  errorPageImage: "/images/ErrorPageImage.webp",
  govActionDefaultImage: "/images/GovActionDefault.webp",
  govActionDelegateImage: "/images/GovActionDelegate.webp",
  govActionListImage: "/images/GovActionList.webp",
  govActionRegisterImage: "/images/GovActionRegister.webp",
  heroImage: "/images/HeroImage.webp",
  proposeGovActionImage: "/images/ProposeGovAction.webp",
  directVoterImage: "/images/GovActionsDirectVoter.webp",
  successImage: "/images/Success.webp",
  warningImage: "/images/Warning.webp",
  warningYellowImage: "/images/WarningYellow.webp",
};
