export const PATHS = {
  createGovernanceAction: "/create_governance_action",
  dashboardGovernanceActionsAction: "/connected/governance_actions/:proposalId",
  dashboardGovernanceActionsCategory:
  "/connected/governance_actions/category/:category",
  dashboardGovernanceActions: "/connected/governance_actions",
  dashboardDRepDirectory: "/connected/drep_directory",
  dashboardDrepDirectoryDrep: "/connected/drep_directory/:dRepId",
  dashboard: "/dashboard",
  delegateTodRep: "/delegate",
  dRepDirectory: "/drep_directory",
  drepDirectoryDrep: "/drep_directory/:dRepId",
  error: "/error",
  faqs: "/faqs",
  governanceActions: "/governance_actions",
  governanceActionsAction: "/governance_actions/:proposalId",
  governanceActionsCategoryAction:
    "/governance_actions/category/:category/:proposalId",
  governanceActionsCategory: "/governance_actions/category/:category",
  guides: "/guides",
  home: "/",
  registerAsdRep: "/register",
  registerAsSoleVoter: "/register_sole_voter",
  retireAsSoleVoter: "/retire_sole_voter",
  stakeKeys: "/stake_keys",
  updateMetadata: "/update_metadata",
};
