export const QUERY_KEYS = {
  getAdaHolderCurrentDelegationKey: "getAdaHolderCurrentDelegationKey",
  getAdaHolderVotingPowerKey: "getAdaHolderVotingPowerKey",
  useGetDRepInfoKey: "useGetDRepInfoKey",
  useGetDRepListInfiniteKey: "useGetDRepListInfiniteKey",
  useGetDRepVotesKey: "useGetDRepVotesKey",
  useGetDRepVotingPowerKey: "useGetDRepVotingPowerKey",
  useGetEpochParamsKey: "useGetEpochParamsKey",
  useGetNetworkMetricsKey: "useGetNetworkMetricsKey",
  useGetNetworkTotalStakeKey: "useGetNetworkTotalStakeKey",
  useGetNetworkInfoKey: "useGetNetworkInfoKey",
  useGetSystemFeaturesKey: "useGetSystemFeaturesKey",
  useGetProposalKey: "useGetProposalKey",
  useGetProposalsInfiniteKey: "useGetProposalsInfiniteKey",
  useGetProposalsKey: "useGetProposalsKey",
  useGetVoteContextFromFile: "useGetVoteContextFromFile",
  useGetDRepVotingPowerListKey: "useGetDRepVotingPowerListKey",
  useGetMetadataResolveKey: "useGetMetadataResolveKey",
  useGetMetadataReportKey: "useGetMetadataReportKey",
  useGetMetadataReportsKey: "useGetMetadataReportsKey",
  useGetGovernanceActionEpochParamsKey: "useGetGovernanceActionEpochParamsKey",
  useGetGovernanceActionMetadataKey: "useGetGovernanceActionMetadataKey",
  useGetGovernanceActionRecordKey: "useGetGovernanceActionRecordKey",
  useGetGovernanceActionHistoryKey: "useGetGovernanceActionHistoryKey",
  useGetGovernanceActionProposalDiscussionKey: "useGetGovernanceActionProposalDiscussionKey",
  useGovernanceActionVerifySignatureKey: "useGovernanceActionVerifySignatureKey",
};

export const MUTATION_KEYS = {
  postValidateKey: "postValidateKey",
  postMetadataRetryKey: "postMetadataRetryKey",
};
