export const QUERY_KEYS = {
  getAdaHolderCurrentDelegationKey: "getAdaHolderCurrentDelegationKey",
  getAdaHolderVotingPowerKey: "getAdaHolderVotingPowerKey",
  useGetDRepInfoKey: "useGetDRepInfoKey",
  useGetDRepListInfiniteKey: "useGetDRepListInfiniteKey",
  useGetDRepVotesKey: "useGetDRepVotesKey",
  useGetDRepVotingPowerKey: "useGetDRepVotingPowerKey",
  useGetEpochParamsKey: "useGetEpochParamsKey",
  useGetNetworkMetricsKey: "useGetNetworkMetricsKey",
  useGetNetworkTotalStakeKey: "useGetNetworkTotalStakeKey",
  useGetNetworkInfoKey: "useGetNetworkInfoKey",
  useGetSystemFeaturesKey: "useGetSystemFeaturesKey",
  useGetProposalKey: "useGetProposalKey",
  useGetProposalsInfiniteKey: "useGetProposalsInfiniteKey",
  useGetProposalsKey: "useGetProposalsKey",
  useGetVoteContextFromFile: "useGetVoteContextFromFile",
  useGetDRepVotingPowerListKey: "useGetDRepVotingPowerListKey",
  useGetMetadataResolveKey: "useGetMetadataResolveKey",
  useGetMetadataReportKey: "useGetMetadataReportKey",
  useGetMetadataReportsKey: "useGetMetadataReportsKey",
  useGetOutcomeEpochParamsKey: "useGetOutcomeEpochParamsKey",
  useGetOutcomeGovActionMetadataKey: "useGetOutcomeGovActionMetadataKey",
  useGetOutcomeGovernanceActionKey: "useGetOutcomeGovernanceActionKey",
  useGetOutcomeGovernanceActionsKey: "useGetOutcomeGovernanceActionsKey",
  useGetOutcomeNetworkMetricsKey: "useGetOutcomeNetworkMetricsKey",
  useGetOutcomeProposalDiscussionKey: "useGetOutcomeProposalDiscussionKey",
  useOutcomeVerifySignatureKey: "useOutcomeVerifySignatureKey",
};

export const MUTATION_KEYS = {
  postValidateKey: "postValidateKey",
  postMetadataRetryKey: "postMetadataRetryKey",
};
