export const PATHS = {
  createGovernanceAction: "/create_governance_action",
  dashboard: "/dashboard",
  dashboardGovernanceActions: "/connected/governance_actions",
  dashboardGovernanceActionsAction: "/connected/governance_actions/:proposalId",
  dashboardGovernanceActionsCategory:
    "/connected/governance_actions/category/:category",
  dashboardDRepDirectory: "/connected/drep_directory",
  dashboardDRepDirectoryDRep: "/connected/drep_directory/:dRepId",
  dRepDirectory: "/drep_directory",
  dRepDirectoryDRep: "/drep_directory/:dRepId",
  editDrepMetadata: "/edit_drep",
  error: "/error",
  faqs: "/faqs",
  governanceActions: "/governance_actions",
  governanceActionsAction: "/governance_actions/:proposalId",
  governanceActionsCategory: "/governance_actions/category/:category",
  governanceActionsCategoryAction:
    "/governance_actions/category/:category/:proposalId",
  guides: "/guides",
  home: "/",
  registerAsdRep: "/register_drep",
  registerAsSoleVoter: "/register_sole_voter",
  retireAsDrep: "/retire_drep",
  retireAsSoleVoter: "/retire_sole_voter",
  stakeKeys: "/stake_keys",
};
