{
 "title": "VVA basic stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Frontend HTTP return codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_service_requests_total{service=\"frontend@docker\"}",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Frontend HTTP requests by return code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by(code) (rate(traefik_service_requests_total{service=\"frontend@docker\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Cardano Node slotInEpoch change rate ofer 5 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_slotInEpoch_int{instance=\"cardano-node:12798\"}[5m])"
    }
   ]
  },
  {
   "title": "Backend HTTP return codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_service_requests_total{service=\"backend@docker\"}",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Backend HTTP requests by return code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum by(code) (rate(traefik_service_requests_total{service=\"backend@docker\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "DB Sync node-db block height difference",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_db_sync_node_block_height{instance=\"cardano-db-sync:8080\"}"
    },
    {
     "expr": "cardano_db_sync_db_block_height{instance=\"cardano-db-sync:8080\"}"
    }
   ]
  },
  {
   "title": "Used disk space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100 - (node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"host.docker.internal:9100\"} * 100 / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"host.docker.internal:9100\"})"
    }
   ]
  },
  {
   "title": "Average disk IO queue depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"host.docker.internal:9100\", device=\"nvme0n1\"}[5m])"
    }
   ]
  },
  {
   "title": "Disk R/W throughput over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"host.docker.internal:9100\", device=\"nvme0n1\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"host.docker.internal:9100\", device=\"nvme0n1\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "System load (avg 5 min)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "node_load5{instance=\"host.docker.internal:9100\"}"
    }
   ]
  }
 ]
}