name: 🐛 Bug report
description: You found a bug!
title: '🐛 '
labels: ["🐛 Bug"]
projects: ["IntersectMBO/30", "IntersectMBO/34"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🌟 **Thank you for contributing to GovTool!**
  - type: markdown
    attributes:
      value: |
        Before submitting a new issue please check the [existing issues](https://github.com/IntersectMBO/govtool/issues) to avoid duplication.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What part of GovTool does this feature affect?
      options:
        - Proposal Pillar
        - Voting Pillar
        - Delegation Pillar
        - Wrapper
        - Other
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: Which GovTool instance were you connected to?
      options:
        - sanchogov.tools
        - dev-sanchogov.tools
        - test-sanchogov.tools
        - stage-sanchogov.tools
        - preview.gov.tools
        - Custom setup
    validations:
      required: true

  - type: input
    id: wallet
    attributes:
      label: Which wallet were you using?
      description: Please provide which wallet and version you were using
      placeholder: |
        Eternl wallet v1.12.6.6 
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please give the context to what you were trying to achieve
      placeholder: |
        I was trying to register as a DRep and the following happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Explain the steps to reproduce
      placeholder: |
          1. Connect wallet
          2. Navigate to the dashboard
          3. Click on "Register as DRep"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description:  A description of the erroneous outcome
      placeholder: |
        A error came up on the screen stating...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A description of what you expect to happen instead
      placeholder: |
        The DRep registration transaction was sent and I was registered
    validations:
      required: true
