name: 💡 Feature idea
description: Idea or request for some feature on the GovTool roadmap
labels: ['💡 Feature idea']
body:
  - type: markdown
    attributes:
      value: |
        ## 🌟 **Thank you for contributing to GovTool!**
  - type: markdown
    attributes:
      value: |
        Before submitting a new issue consider [starting a new discussion](https://github.com/IntersectMBO/govtool/discussions/new?category=ideas).

  - type: dropdown
    id: area
    attributes:
      label: Feature area
      description: What part of GovTool does this feature affect?
      options:
        - Proposal Pillar
        - Voting Pillar
        - Delegation Pillar
        - Wrapper
        - Other
        - Not sure
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What?
      description: What is this feature?
      placeholder: |
        For example describe a new API endpoint, a change in wording,
        a new configuration option, ...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Why do we need or want this feature?
      placeholder: |
        Give context and describe the problem, challenge or opportunity you see
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: How?
      description: How can we realize this feature?
      placeholder: |
        Which technical solutions, libraries or systems should be used, which
        components need to change, steps how to implement this, ...
    validations:
      required: true
