name: 💡 Feature idea
description: Suggest a new feature or enhancement for GovTool.
title: "💡 "
labels: ["💡 Feature idea", "Needs UX Review"]
projects: ["IntersectMBO/30", "IntersectMBO/34"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🌟 **Thank you for contributing to GovTool!**
  
  - type: markdown
    attributes:
      value:
        Please fill out the following details.
  
  - type: textarea
    id: problem-statement
    attributes:
      label: "💡 Suggestion or feature"
      description: "Please describe the user need, idea, or pain point."
      placeholder: "Example: Users would benefit from having X functionality, so they can do Y..."
    validations:
      required: true
  
  - type: textarea
    id: user-impact
    attributes:
      label: "Who does this help?"
      description: "Which users will benefit from this feature? How does it improve their experience?"
      placeholder: "Example: This feature will help first-time users onboard faster..."
    validations:
      required: true
  
  - type: textarea
    id: dependencies
    attributes:
      label: "How might we do this?"
      description: "Suggestions on implementation"
      placeholder: "Example: Add a button that says GO to the home page"
    validations:
      required: false
  
  - type: textarea
    id: other-info
    attributes:
      label: "Anything else you might want to add?"
      description: "Free text box for any comments"
      placeholder: "I love GovTool, and so does my dog!"
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: user-story
    attributes:
      label: (Optional) User Story with acceptance criteria
      description: See GovTool examples [here](https://github.com/IntersectMBO/cardano-test-plans/blob/main/userStoryInventoryChangHF.md#2g-delegate-to-self-for-registered-dreps).
      placeholder: |
        As a [ada holder | DRep | Direct voter], I want [some goal] so that [some reason].
    validations:
      required: false