version: '3.9'

services:
  metadata-validation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata-validation
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/dist
