global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'govtool'
scrape_configs:
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['traefik:8082']
  - job_name: 'cardano'
    scrape_interval: 5s
    static_configs:
      - targets: ['cardano-node:12798']
  - job_name: 'cardano_db_sync'
    scrape_interval: 5s
    metrics_path: /
    static_configs:
      - targets: ['cardano-db-sync:8080']
  - job_name: 'host'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']
